services:
  backend:
    image: identaler/perszeplus:app
    ports:
      - "8000:80"
    volumes:
      - ./perszePlus:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=user
      - DB_PASSWORD=asd

  frontend:
    image: identaler/perszeplus:web
    ports:
      - "3000:80"
    volumes:
      - ./vite-project:/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asd
      MYSQL_DATABASE: persze
      MYSQL_USER: user
      MYSQL_PASSWORD: asd
    ports:
      - "3306:3306"

  phpmyadmin:  
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"  
    environment:
      PMA_HOST: db  
      PMA_USER: user  
      PMA_PASSWORD: asd  
    depends_on:
      - db  
