services:
  backend:
    image: identaler/perszeplus:app
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./perszePlus:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_URL=${APP_URL}

  frontend:
    image: identaler/perszeplus:web
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./vite-project:/app
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:  
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${PMA_HOST}  
      PMA_USER: ${PMA_USER}  
      PMA_PASSWORD: ${PMA_PASSWORD}  
    depends_on:
      - db
