services:
  backend:
    image: identaler/perszeplus:app
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./perszePlus:/var/www/html
    depends_on:
      - db
    environment:
<<<<<<< Updated upstream
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_URL=${APP_URL}
=======
      - DB_HOST=db
      - DB_USERNAME=user
      - DB_PASSWORD=asd
      - APP_URL=http://62.84.181.127:8000
>>>>>>> Stashed changes

  frontend:
    build:
      context: ./vite-project
      args:
        VITE_BACKEND_URL: http://backend:80 # Injecting the variable statically

    image: identaler/perszeplus:web
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./vite-project:/app
    environment:
<<<<<<< Updated upstream
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
=======
      - VITE_API_BASE_URL=http://backend:80
>>>>>>> Stashed changes

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:  
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
<<<<<<< Updated upstream
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${PMA_HOST}  
      PMA_USER: ${PMA_USER}  
      PMA_PASSWORD: ${PMA_PASSWORD}  
    depends_on:
      - db
=======
      - "3306:3306"

  phpmyadmin:  
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"  
    environment:
      PMA_HOST: db  
      PMA_USER: user  
      PMA_PASSWORD: asd  
    depends_on:
      - db  
>>>>>>> Stashed changes
