services:
  backend:
    image: identaler/perszeplus:app
    ports:
      - "8000:80"
    volumes:
      - ./perszePlus:/var/www/html
    depends_on:
      - db

  frontend:
    image: identaler/perszeplus:web
    ports:
      - "3000:80"
    volumes:
      - ./vite-project:/app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asd
      MYSQL_DATABASE: persze
      MYSQL_USER: user
      MYSQL_PASSWORD: asd
    ports:
      - "3306:3306"
